spring.application.name=portal_solicitacoes

# Datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/portal_solicitacoes
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate — Flyway controla o DDL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=desafio
spring.jpa.show-sql=true

# Flyway é configurado no arquivo FlywayConfig.java